### ISSUE TITLE
Creación y actualización de pre roadmap para el sistema de gestión académica vigencia 2024, sprint dos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#16]
Se requiere realizar la Creación y actualización de pre roadmap para el sistema de gestión académica vigencia 2024, sprint dos

**Sub Tareas**

- [ ] Análisis de requerimientos necesarios para establecer el pre roadmap para el sistema de gestión académica vigencia 2024, sprint dos
- [ ] Creación y documentación de issue para sistema de gestión académica vigencia 2024, sprint dos

**Criterios de aceptación**

- [ ] Análisis de actividades
- [ ]  Creación de issues

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.
