### ISSUE TITLE
Creación de reporte general de aspirantes por proyectos curricular, estado de pago del recibo e información característica mediante la librería excelize

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#164]
Se requiere realizar la Creación de reporte general de aspirantes por proyectos curricular, estado de pago del recibo e información característica mediante la librería excelize

**Sub Tareas**

- [x] Revisión de controlador de consulta generado en la issue #151 para la consulta de información necesaria
- [x] Creación del reporte con la información consulta por el controlador, mantener el mismo encabezado realizado en la issue #150 
- [x] Creación del controlador para la creación del reporte, y archivo base 64 con la información del reporte
- [x] Integración del reporte en el componente desarrollado en la issue #150 

**Criterios de aceptación**

- [x] Analisis del controlador existente
- [x] Creación del controlador
- [x] Implementación del reporte en el cliente

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación 

## Nuevo concepto de consulta BACK

Como se puede apreciar en la documentación para realizar la consulta al endpoint de reportes udistrital/sga_documentacion#136

### En el caso de el nuevo reporte:

4 -> Reporte general por periodo y nivel


#### Ejemplo de una consulta funcional
{
"Proyecto": 2 -> En este caso al definir el tipo de reporte en 4 el proyecto en realidad corresponde al id de el nivel a consultar en este caso (posgrado)
"Periodo": 9, -> periodo para realizar la consulta
"Reporte": 4, -> tipo de reporte que recibe el nivel y el periodo
"Columnas": ["A", "B", "C", "D"] -> columnas que se deseen de el reporte
}

## Adición funcionalidad FRONT

### Los campos de facultad y proyecto no son requeridos a la hora de generar el reporte general

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/3c19518f-d734-4357-9e71-76ce3f7afab3)

De esta manera se realiza un ajuste al formulario para que sea reactivo según la selección de el reporte a consultar

### Despliegue de tabla con títulos de el nivel para reafirmar la consulta general

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/a960977d-240a-43a5-a619-a3fbf66bdc46)

### Visualización de el reporte 

![image](https://github.com/udistrital/sga_documentacion/assets/73076138/0cfa5d02-54b3-47d3-8fe7-6d1de0539d45)

El visualizador presenta problemas de despliegue, debido a configuración actual de el root.

### Acciones

* El icono de pdf permite descargar el reporte en formato .pdf
* El icono de tabla permite descargar el reporte en formato .xlsx
* El icono de el ojo permite realizar una previsualización de el reporte en .pdf

### Mas información de los reportes dinámicos ver udistrital/sga_documentacion#150

**Comment by Moreraz20** [comment]
# Issue finalziada.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en pruebas
