### ISSUE TITLE
Implementación de flujo de trazabilidad de seguemiento de cambio de estado de inscripción en los procesos de inscripción aspirante, revisión de documentos y cambio de estado administrativos con registro de id de tercero

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#301]
Se requiere realizar la Implementación de flujo de trazabilidad de seguemiento de cambio de estado de inscripción en los procesos de inscripción aspirante, revisión de documentos y cambio de estado administrativos con registro de id de tercero, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Teniendo en cuenta #286 se debe implementar el registro de cambio de estados de inscripción en el flujo de inscripción del aspirante, se debe realizar al cambiar de estado de inscripción solicitada a inscrito (botón inscribirme), el registro debe hacerle con el id del tercero identificado en el cliente

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/8bd601f9-fc6a-4219-9738-82497e1ca736)

- [x] Teniendo en cuenta #286 se debe implementar el registro de cambio de estados de inscripción en el flujo de revisión de documentos vista administrativa (admisiones, evaluación de documentos de inscritos), este registro de estado se debe realizar al realizar una observación en algún documento, cambio de estado inscrito a inscrito con observación (botón rechazar documento), el registro debe hacerle con el id del tercero identificado en el cliente

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/ecde4dbe-5567-44fc-92ca-a58d1a739a9c)

- [x]  Teniendo en cuenta #286 se debe implementar el registro de cambio de estados de inscripción en el flujo de cambio manual de estado vista administrativos (admisiones, lista de aspirantes), este registro de estado se debe realizar al realizar un cambio manual en el select de estados , el registro debe hacerle con el id del tercero identificado en el cliente

![image](https://github.com/udistrital/sga_documentacion/assets/43799065/4bb112eb-af97-4554-87a2-41934b2fe619)
 

**Criterios de aceptación**

- [x] Ajuste de flujo con el registro de cambio de estados a nivel cliente
- [x] Ajuste de flujo con el registro de cambio de estados a nivel mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by diegofceliv** [comment]
### Documentación:

Se realizan algunas pruebas de la interacción directa con los servicios modificados en el mid, para comprobar el registro del cambio de los estados en el tiempo, como lo podemos ver en la siguiente grafica, una vez se crea una inscripcion, se crea un primer registro con el estado anterior vacio y con el nuevo estado referenciado:

![image](https://github.com/udistrital/sga_documentacion/assets/131480252/09feca63-b493-4b98-bd26-1cf37e3ecd9b)

En caso de realizar cambios de estados se visualiza como estos avanzan en el tiempo

**Comment by diegofceliv** [comment]
Documentación pruebas desde el front:

Se realiza la prueba en la creación de una inscripción:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/4e711374-6ab6-47e2-b2ff-868ab2a9a43c)

Se generó la inscripción nuevo 805

La inscripción la crea el usuario `59806`
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/6e52cf64-8d40-457a-916d-a3669ed26ee1)

Se valida el registro en la tabla del historico:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/2e8bbb8e-60c1-433f-a66b-bea7837edd6f)

Se valida flujo al completar la inscripcion:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/444c0a2e-6ed2-46cb-adaf-b517f0c9c47e)

En la consola se ve que el consumo al servicio que actualiza el estado fue exitoso
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/a31bc77a-de3e-4341-9946-da7766429bbf)

En la Base se datos se confirma el historico:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/0d1fdc2f-a32e-4a65-9295-19d0d0ab6335)

Se prueba flujo para actualizar estado desde admisiones:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b6752ca7-bc3e-49af-bd62-81a5f0ed757d)

Cambio a admitido:
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/c72928de-755d-4f27-aa20-a2937330055f)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/b30ec106-e44e-49a0-939c-f9ea24e007bf)

Historico (Se realizaron cambios adicionales de estado despues del ADMITIDO)
![image](https://github.com/udistrital/sga_documentacion/assets/131480252/fb94cb2b-7915-4f23-9864-c5b554dd14f9)

**Comment by diegofceliv** [comment]
Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, queda pendiente el despliegue en test para unificación de cambios con otras issue
