### ISSUE TITLE
Ajuste para guardar historico de estados en todo el proceso de inscripcion y admision de pregrado

### ISSUE THREAD

**Issue by brayaned** [udistrital/sga_documentacion#368]
Se requiere realizar los ajustes necesarios para guardar en la nueva tabla desarrollada en el modelo de inscripción el historico de estados en cada una de las etapas del proceso de inscripción y admisión.

**Sub Tareas**

- [ ]  Ajustes para guardar el histórico de estados en inscripcion_crud
- [ ]  Documentar actividad

**Criterios de aceptación**

- [ ]  Ajustes cliente
- [ ]  Ajustes mid 
- [ ]  Documentación de issue

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by norbeydanilo** [comment]
@JaredPeralta Actualizar con el estado de la issue y finalizar.

**Comment by IbzanJared** [comment]
### Actualización 
Se realizan los cambios solicitados en donde en cada punto que se requiere actualizar el estado de la inscripción en el flujo de admisiones y en el flujo de inscripción se llama a la función actualizarEstadoInscripcion en donde se llama al endpoint encargado de manejar la nueva tabla de inscripción que se llama inscripcion_evolucion_estado encargada de llevar el histórico de los estados de esa inscripción.
