### ISSUE TITLE
Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo, segunda parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#434]
Se requiere realizar la Prueba de integridad y consistencia en el modulo de admisiones, ajustes, establecer data en el ambiente de pruebas y comprobación de flujo de cada submódulo, segunda parte la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Realizar a finalización de la prueba de integridad realizada en la issue #415 
- [x] Realizar ajustes a bug encontrados
- [x] Documentar los posibles bug que requieran atención adicional

**Criterios de aceptación**

- [x] Establecer la data de pruebas
- [x] Realizar la prueba de integridad y consistencia del modulo de admisiones

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by bfmu** [comment]
- [x] creación calendario academico.
  - `Calendario academico para: Postgrado`
  - `Periodo academico: 2025-1`
  - `Resolucion de creacion: 531`
  - `Año de resolucion: 2024`
  - [x] crear proceso
    - `ADMISIONES`
    - [x] crear actividad
      - `Fechas de pago para la inscripción de aspirantes a cada período académico.`
      - `Inscripción de aspirantes a través de la página Web.`
- [x] creación proyecto curricular.
  - codigo SNIES: `3559`
  - nombre: `ESP. INGENIERIA DEL SOFTWARE`
- [x] creación criterios, subcriterios.
  - [x] definir criterios.
    - `Ya estaban definidos.`
  - [x] asignar criterios al proyecto curricular.
    - ` Entrevista, Hoja de vida, Examen` --> `ESP. INGENIERIA DEL SOFTWARE`
- [x] creación de aspirantes de pruebas.
  - [x] crear usuarios.
    - usuario101
    - usuario102
    - usuario103
     ```js
    [
      {
        "primer_nombre": "Luis",
        "segundo_nombre": "Fernando",
        "primer_apellido": "García",
        "segundo_apellido": "Torres",
        "tipo_documento": "Cédula de ciudadanía (CC)",
        "numero_documento": "9876543210",
        "verificar_numero_documento": "9876543210",
        "fecha_expedicion_documento": "17/10/2023",
        "fecha_nacimiento": "15/10/2005",
        "sexo": "Masculino",
        "correo_electronico": "usuario101@udistrital.edu.co",
        "telefono": "3201234567",
        "IdInscripcion": 813
      },
      {
        "primer_nombre": "Ana",
        "segundo_nombre": "María",
        "primer_apellido": "Rodríguez",
        "segundo_apellido": "López",
        "tipo_documento": "Cédula de ciudadanía (CC)",
        "numero_documento": "8765432109",
        "verificar_numero_documento": "8765432109",
        "fecha_expedicion_documento": "22/11/2023",
        "fecha_nacimiento": "20/11/2005",
        "sexo": "Femenino",
        "correo_electronico": "usuario102@udistrital.edu.co",
        "telefono": "3211234567",
        "IdInscripcion": 814
      },
      {
        "primer_nombre": "Carlos",
        "segundo_nombre": "Alberto",
        "primer_apellido": "Martínez",
        "segundo_apellido": "Rivera",
        "tipo_documento": "Cédula de ciudadanía (CC)",
        "numero_documento": "7654321098",
        "verificar_numero_documento": "7654321098",
        "fecha_expedicion_documento": "07/12/2023",
        "fecha_nacimiento": "05/12/2005",
        "sexo": "Masculino",
        "correo_electronico": "usuario103@udistrital.edu.co",
        "telefono": "3221234567",
        "IdInscripcion": 815
      }
    ]
    ```
---
  - [x] udistrital/sga_documentacion#415
  - [x] Tener activo el tipo de inscripcion `Nueva - pregrado`
  - [x] Definir la SUITE 
  - [x] Crear derecho pecuniario `concepto de inscripción`
  - [x] inscribirse a `INGENIERIA DE SISTEMAS`
  - [x] pagar el recibo.
  - [x] continua en udistrital/sga_documentacion#440
  

# PROCESO

1. ✅ En el modulo de listar tipos de inscripcion en `admisiones` se agregado la funcionalidad de poder habilitar de nuevo un tipo de inscripcion.  ![Kapture 2024-08-22 at 07 30 16](https://github.com/user-attachments/assets/4c3df72f-8b10-4f5b-89a9-ac2390c41001)
2. ✅ Se ajusta el controlador, se corrigen varios bugs y se implementa la funcionalidad de validar el periodo academico, ademas si el ciclo del periodo es 1, se toma el año anterior, acontinuacion una demostracion. ![Kapture 2024-08-22 at 19 34 31](https://github.com/user-attachments/assets/2f8af04c-80c9-4822-a768-a86676076911)
3. ❌ Editar un derecho pecunario falla. ![image](https://github.com/user-attachments/assets/3d85619d-ed57-4739-8074-4c66241a3144)  ![image](https://github.com/user-attachments/assets/4bbf4635-14f8-48b8-975e-cc5d1ede69f5)
4. ❌ Modificar la consulta de la vigencia en el front para que consulte la vigencia anterior si el ciclo es 1, osea el periodo es 1.  ![image](https://github.com/user-attachments/assets/43250fe5-70ec-4977-8687-05a1168a800a)
5. ❌ En `sga_cliente_proyecto_curricular_mf` Cuando se guarda un archivo se le asigna un nombre, el cual no puede contener caracteres especiales, en este caso se estaba generando el nombre con un `.`, se realiza la limpieza del nombre y luego si se procede a guardar.  <img width="844" alt="image" src="https://github.com/user-attachments/assets/b7802d44-6c43-4218-ae98-75f045b9b729">  ![image](https://github.com/user-attachments/assets/72ee302c-8147-4f82-bdc4-60e60b467b47) ✅  **SOLUCIONADO** <img width="614" alt="image" src="https://github.com/user-attachments/assets/74f94cc9-df17-4c72-8643-d46e510a4766">

**Comment by bfmu** [comment]
continua en udistrital/sga_documentacion#440
---
# TERMINADO
