### ISSUE TITLE
Presentación para confirmación proceso de inscripción y admisión y migración de backlog a roadmap

### ISSUE THREAD

**Issue by norbeydanilo** [udistrital/sga_documentacion#44]
Se requiere crear una breve presentación formal que incluya los flujos definidos en el levantamiento de requerimientos para los módulos de inscripción y admisión para pregrado, con el propósito de ser socializada con las partes interesadas y obtener la aprobación para su posterior impelementación.

Así mismo, se debe dar por completada la migración de los elementos de trabajo del pre roadmap al roadmap que formalmente se está trabajando por el equipo.

**Sub Tareas**

- [ ] Presentación formal con flujos levantados, descripción de los procesos.
- [ ] Finalización de migración hacia el roadmap del proyecto.

**Criterios de aceptación**

- [ ] Presentación en formato pptx o pdf.
- [ ] Roadmap actualizado.

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Incluye la descripción y criterios de aceptación referente al análisis y/o diseño.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] La documentación asociada, si aplica, está disponible y es entendible.

**Definition of Done - DoD - Análisis/Diseño**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico/SoSM.
- [ ] Artefacto solicitado satisface la necesidad.

**Comment by cearomeroc01** [comment]
De acuerdo al requerimiento se crea el documento correspondiente para la presentación a los stakeholders del proyecto, a continuación el enlace correspondiente del [documento.](https://udistritaleduco-my.sharepoint.com/:p:/g/personal/computo_udistrital_edu_co/ESyFVp5OR1lFrGCL0COxQ8ABkF9FjbgEEzAHPUj4m8750w?e=VcNSxE)

**Comment by cearomeroc01** [comment]
De acuerdo a las actividades realizadas relacionadas con el levantamiento, verificación y confirmación de procesos, flujos de información, se ha editado la siguiente acta de reunión con el respectivo soporte de asistencia presencial de los stakeholders del proyecto [enlace documentos](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EiYzGviR_xZHn08xN2eadc8BzuaEoWM9QkRWOLsbaRDGbw?e=D4rJGx)
