### ISSUE TITLE
Ajustes de estilos de componentes modulo de formularios dinámicos con los estilos establecidos en el sistema 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#482]
Se requiere realizar el Ajustes de estilos de componentes modulo de formularios dinámicos con los estilos establecidos en el sistema, la issue debe  cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Ajustar los estilos del componente de listar formularios según lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127
- [x] Ajustar los estilos del componente CRUD formularios según lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127
- [x] Ajustar los estilos del componente de visualización formularios según lo definido en la issue https://github.com/udistrital/sga_documentacion/issues/415#issuecomment-2282312127

**Criterios de aceptación**

- [x] Ajustar estilos

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by Moreraz20** [comment]
# Documentación

## Cambio de estilos para los componentes, listar, crud y view

![image](https://github.com/user-attachments/assets/f00417f6-0893-4476-9152-a2adc20809d6)

![image](https://github.com/user-attachments/assets/5a289e0f-4b1f-41ae-88ce-9fd8fa52cd30)

![image](https://github.com/user-attachments/assets/864c5055-31c3-405e-abe6-7883065d9aa3)

![image](https://github.com/user-attachments/assets/f06c02c9-84e4-4cc7-b5c2-88a79cd69399)

![image](https://github.com/user-attachments/assets/16e37a01-4af6-4af3-a7bd-53bc1a65eed2)

**Comment by Moreraz20** [comment]
# Issue finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se aprueba el pr y se despliega en test
