### ISSUE TITLE
Revisión, análisis y  Sincronización de ajustes en el ambiente de monolítico al ambiente de micro clientes 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#494]
Se requiere realizar la Revisión, análisis y  Sincronización de ajustes en el ambiente de monolítico al ambiente de micro clientes, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Revisar los ajustes realizados en la issue #218 en el micro cliente de admisiones y micro mid de admisiones, si no se realizo el ajuste a nivel de micro servicios realizar el ajuste.
- [x] Revisar los ajustes realizados en la issue #438 en el micro cliente de inscripciones y micro mid de inscripciones, si no se realizo el ajuste a nivel de micro servicios realizar el ajuste.
- [x] Revisar los ajustes realizados en la issue #442  en el micro cliente de inscripciones y micro mid de inscripciones, si no se realizo el ajuste a nivel de micro servicios realizar el ajuste.
- [x] Revisar los ajustes realizados en la issue #468  en el micro cliente de admisiones y micro mid de admisiones, si no se realizo el ajuste a nivel de micro servicios realizar el ajuste.
- [x] Revisar los ajustes realizados en la issue #456  en el micro cliente de admisiones y micro mid de admisiones, si no se realizo el ajuste a nivel de micro servicios realizar el ajuste.

**Criterios de aceptación**

- [x] Analizar, revisar y ajustar los desarrollos de producción a la arquitectura de micros servicios 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
Se realizó el ajuste correspondiente en la línea **`color="primary" [checked]="c.valor" (change)="onChangeCheckBox($event, c); c.valor = !c.valor">`**. Se evidenció que la sección estaba presente, pero comentada con los cambios antiguos. Se procedió a activar la sección del **`checkbox`**, junto con el FIX ya aplicado, y se agregó la propiedad **` onChangeCheckBox: any;`** en el archivo TypeScript.

**Comment by OscarLozano01** [comment]
**Pasos para instalar nvm en Windows:**


1. Descargar nvm.

Para poder instalar la herramienta Node Version Manager en un entorno Windows debemos descargar un [archivo zip](https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.zip) que contiene el asistente de instalación.

2. Instalar nvm.

En la carpeta Descargas o Downloads en Windows, descomprime el archivo nvm-setup.zip y haz doble clic en el archivo nvm-setup.

3. Asistente de instalación.

Cuando se abre el asistente de instalación, dale clic al botón next un par de veces y, al final verás un botón install al cual también que darle clic. Después de eso, solo espera a que la barra de progreso termine.

4. Instalar las versiones de Node.js que estes necesitando en este caso usaremos la versión 12 y la version 20:

Abre la línea de comando de Windows

```shell
nvm install 12
```
Esto instalará la última versión disponible de la serie 12.x.x.

5. Instalar Node.js versión 20:

Abre la línea de comando de Windows

```shell
nvm install 20
```
Esto instalará la última versión disponible de la serie 20.x.x.

6. Verificar las versiones instaladas:

Abre la línea de comando de Windows

```shell
nvm ls
```
7. Cambiar entre versiones de Node.js:

Abre la línea de comando de Windows

```shell
nvm use 12
```

```shell
nvm use 20
```

8. Establecer una versión predeterminada:

Abre la línea de comando de Windows

```shell
nvm alias default 12  # O la versión que desees
```

**Comment by OscarLozano01** [comment]
Se replica FIX de la issues/456 en el MF de admisiones commit de arriba 👆

**Comment by OscarLozano01** [comment]
Revisión del BUG de la issue #218 del proyecto SGA_CLIENTE en la arquitectura monolítica, asegurando que esté correctamente implementada en el microservicio de Admisiones.

Se evidencia que en la función  `activeCriterios()` tiene el query tal cual en la solución al bug.

```
    this.evaluacionService
      .get(
        "requisito_programa_academico?query=Activo:true,ProgramaAcademicoId:" +
          this.proyectos_selected +
          ",PeriodoId:" +
          this.periodo.Id
      )
```

![image](https://github.com/user-attachments/assets/213cdcb3-5d24-473f-8ee0-e507b0b410fb)

Se evidencia que en la función  `async guardar` tiene la misma lógica implementada correctamente.

![image](https://github.com/user-attachments/assets/44236979-ded7-4e85-b5f4-1e48c093c78f)

Se verifica en environment.development.ts este el Endpoint correctamente.

![image](https://github.com/user-attachments/assets/f8f3762c-0da7-4500-8299-d996ffe5e290)

Se verifica en environment.ts este el Endpoint correctamente.

![image](https://github.com/user-attachments/assets/726873d9-f10c-4c6f-b38d-1693ac3d0973)

**Comment by OscarLozano01** [comment]
Se asginan los id del Ambiente de Producción Correctamente:

```
InfoComplementariaTelefono := map[string]interface{}{
	"Id": 48,
}
InfoComplementariaCorreo := map[string]interface{}{
	"Id": 50,
}
InfoComplementariaDireccion := map[string]interface{}{
	"Id": 51,
}
```

![image](https://github.com/user-attachments/assets/07e4999a-e512-41d5-bc96-910774221e67)

**Comment by OscarLozano01** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se despliega en ambiente de pruebas y se da por finalizada la issue
