### ISSUE TITLE
Creación de informe de cierre  milestones Ciclo de vida académica, Plan trabajo docente según el formato establecido 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#536]
Se requiere realizar la Creación de informe de cierre SGA milestones Ciclo de vida académica, Plan trabajo docente según el formato establecido, la issue debe cumplir con los siguientes requerimientos: 

**Sub Tareas**

- [x] Registrar en el documento de informe final la información de identificación del proyecto, la descripción del hito y el estado inicial del hito, segun sea el hito de la issue 

![image](https://github.com/user-attachments/assets/b1d60825-73ee-417b-85c7-bd13253ef9f3)

- [x] Registrar en el documento de informe final la información de Apis ajustadas y desarrollados en el hito 

![image](https://github.com/user-attachments/assets/99a78488-21d5-4551-ad93-aea0cddc832b)

- [x] Registrar en el documento de informe final la información de cronograma de actividades del hito

![image](https://github.com/user-attachments/assets/91c025f5-1850-40aa-b372-c9656d9d8bc7)

- [x] Registrar en el documento de informe final la información de diagnostico final del hito

![image](https://github.com/user-attachments/assets/1c604e95-0dbd-49a8-a37b-dfa75fe08b47)

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EadvznN_nhhOk7XT4HKWi-YBmE2Hqd0gdrAQXTUEh-dqpA?e=I21S1n

- [x] Registrar en el documento de informe final la información de evidencias de desarrollo en sistema capturas de pantalla segun su hito asignado 

![image](https://github.com/user-attachments/assets/9036ce4f-4c10-4fe8-9dff-1bcfcecbf45a)

**Criterios de aceptación**

- [x] Documentar  el informe de cierre SGA

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by K3vinchaparro** [comment]
### **Creación de informe de cierre milestones Ciclo de vida académica, Plan trabajo docente según el formato establecido**

>[!NOTE]
> - Informe de ciclo de vida académica y plan trabajo docente

---

    - Ciclo de vida académica 
---

Descripciones y apis modificadas 

![image](https://github.com/user-attachments/assets/2b67640a-1c15-425b-9b6d-e684c0768ce4)

Cronograma 

![image](https://github.com/user-attachments/assets/0f320d2d-db67-41cb-a1c2-2ed4a36f27d7)

Diagnóstico 

![image](https://github.com/user-attachments/assets/482be329-2550-402e-bb20-5de3ed8ca0d5)

Evidencias

![image](https://github.com/user-attachments/assets/6260d45d-0e32-49d4-8b9b-5fe7e0e26aa4)

---


    - Plan trabajo docente
    
---

Descripciones y apis modificadas 

![image](https://github.com/user-attachments/assets/70894ff4-7bf8-4460-866c-89981399ea4a)

Cronograma 

![image](https://github.com/user-attachments/assets/c77f18b5-c0d5-427f-b109-17a3372790fa)

Diagnóstico 

![image](https://github.com/user-attachments/assets/c51b00d5-fa23-4293-98a3-3970e950e28d)

Evidencias

![image](https://github.com/user-attachments/assets/76e8f3a5-1b55-4e69-9da5-cb16c234e094)

---

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Informe técnico ciclo de vida académica 

---

 Informe técnico ciclo de vida académica (Horarios, Plan docente, Espacios académicos)


https://github.com/user-attachments/assets/ce6b817d-904b-4318-a115-58a0816cc5bb

**Comment by K3vinchaparro** [comment]
>[!NOTE]
> - Informe técnico ciclo de Syllabus y Derechos pecuniarios

**Comment by K3vinchaparro** [comment]
### **Issue finalizada**

**Comment by fabianbarreto02** [comment]
Se revisa la realización del informe de finalización, se da por finalizada la issue
