### ISSUE TITLE
Creación de informe de cierre SGA milestones Arquitectura, Syllabus según el formato establecido

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#537]
Se requiere realizar la Creación de informe de cierre milestones Arquitectura, Syllabus según el formato establecido, la issue debe cumplir con los siguientes requerimientos:

**Sub Tareas**

- [x] Registrar en el documento de informe final la información de identificación del proyecto, la descripción del hito y el estado inicial del hito, segun sea el hito de la issue 

![image](https://github.com/user-attachments/assets/b1d60825-73ee-417b-85c7-bd13253ef9f3)

- [x] Registrar en el documento de informe final la información de Apis ajustadas y desarrollados en el hito 

![image](https://github.com/user-attachments/assets/99a78488-21d5-4551-ad93-aea0cddc832b)

- [x] Registrar en el documento de informe final la información de cronograma de actividades del hito

![image](https://github.com/user-attachments/assets/91c025f5-1850-40aa-b372-c9656d9d8bc7)

- [x] Registrar en el documento de informe final la información de diagnostico final del hito

![image](https://github.com/user-attachments/assets/1c604e95-0dbd-49a8-a37b-dfa75fe08b47)

https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EadvznN_nhhOk7XT4HKWi-YBmE2Hqd0gdrAQXTUEh-dqpA?e=I21S1n

- [x] Registrar en el documento de informe final la información de evidencias de desarrollo en sistema capturas de pantalla segun su hito asignado 

![image](https://github.com/user-attachments/assets/9036ce4f-4c10-4fe8-9dff-1bcfcecbf45a)

**Criterios de aceptación**

- [x] Documentar  el informe de cierre SGA

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/5fb8c59c-2c81-42c3-82af-3cec06e4050c)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/800ab89e-e746-4bab-9646-0498b7f38827)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/0bdc9cd2-b77d-4959-8ca1-ebd9af8efe48)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/71374af4-6315-4f3c-b522-e51738e8131d)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/85c36913-6a46-43ed-88dc-9cdf34c5440f)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/5ec04efb-b079-4a40-90e3-52b928d5bb3c)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/d61ace38-2384-414e-b22a-37320220963d)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/88c3754f-d90a-4a68-af1a-5961b80024e3)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/5c057f0e-8242-4f3a-8d2f-01569009edc7)

**Comment by OscarLozano01** [comment]
![image](https://github.com/user-attachments/assets/3fa09cc3-0e71-416a-991b-52a83f7f5f83)

**Comment by OscarLozano01** [comment]
### Issue Finalizada

**Comment by fabianbarreto02** [comment]
Se revisa la realización del informe de finalización, se da por finalizada la issue
