### ISSUE TITLE
Migración de Api MID para el proceso de plan docente a arquitectura a micro MID

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_documentacion#78]
Se requiere realizar la Migración de Api MID para el proceso de plan docente a arquitectura a micro MID

**Sub Tareas**

- [x] Documentar la creación del api en el repositorio https://github.com/udistrital/sga_plan_trabajo_docente_mid
- [x] Migrar la logica del api general al api con arquitectura de micro mid, desacoplar la lógica a una carpeta de servicies
- [x] Ajustar el consume de librerias de captura de error con util_oas 

**Criterios de aceptación**

- [ ] Creación del api MID
- [ ] Documentar la APiMID

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias están identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
@NeFaWaltPint Documentar

**Comment by NeFaWaltPint** [comment]
### Swagger nuevo micro mid
![imagen](https://github.com/udistrital/sga_documentacion/assets/31144689/7022f97b-9c6b-482a-abe9-930b4c241f40)

### Todos sus parámetros de consulta se manejan en formato query.
:x: -> Antigua ruta sga_mid | :white_check_mark: -> Nueva ruta micromid

url_mid/v1...

- :x: POST /reportes/plan_trabajo_docente/{docente_id}/{vinculacion_id}/{periodo_id}/{carga}
- :white_check_mark: GET /reporte/plan-trabajo-docente?docente=1&vinculacion=1&periodo=1&carga=C
---
- :x: POST /reportes/verif_cump_ptd/{vigencia}/{proyecto}
- :white_check_mark: GET /reporte/verificacion-cumplimiento-ptd?vigencia=1&proyecto=1
---
- :x: PUT /plan_trabajo_docente/aprobacion_preasignacion
- :white_check_mark: PUT /preasignacion/aprobar
---
- :x: GET /plan_trabajo_docente/asignaciones/{vigencia}
- :white_check_mark: GET /asignacion/?vigencia=1
---
- :x: GET /plan_trabajo_docente/asignaciones_docente/{docente}/{vigencia}
- :white_check_mark: GET /asignacion/docente?docente=1&vigencia=1
---
- :x: GET /plan_trabajo_docente/copiar_plan/{docente}/{vigenciaAnterior}/{vigencia}/{vinculacion}/{carga}
- :white_check_mark: GET /plan/copiar?docente=1&vigenciaAnterior=1&vigencia=1&vinculacion=1&carga=1
---
- :x: GET /plan_trabajo_docente/disponibilidad/{salon}/{vigencia}/{plan}
- :white_check_mark: GET /espacio-fisico/disponibilidad?salon=1&vigencia=1&plan=1
---
- :x: GET /plan_trabajo_docente/docente_documento/{documento}/{vinculacion}
- :white_check_mark: GET /docente/documento?documento=1&vinculacion=1
---
- :x: GET /plan_trabajo_docente/docentes_nombre/{nombre}/{vinculacion}
- :white_check_mark: GET /docente/nombre?nombre=1&vinculacion=1
---
- :x: GET /plan_trabajo_docente/espacios_fisicos_dependencia/{dependencia}
- :white_check_mark: GET /espacio-fisico/dependencia?dependencia=1
---
- :x: GET /plan_trabajo_docente/grupos_espacio_academico/padre/{padre}
- :white_check_mark: GET /espacio-academico/grupo-padre?padre=1
---
- :x: GET /plan_trabajo_docente/grupos_espacio_academico/{padre}/{vigencia}
- :white_check_mark: GET /espacio-academico/grupo?padre=1&vigencia=1
---
- :x: PUT /plan_trabajo_docente/plan
- :white_check_mark: PUT /plan/
---
- :x: GET /plan_trabajo_docente/plan/{docente}/{vigencia}/{vinculacion}
- :white_check_mark: GET /plan/?docente=1&vigencia=1&vinculacion=1
---
- :x: GET /plan_trabajo_docente/planes_preaprobados/{vigencia}/{proyecto}
- :white_check_mark: GET /plan/preaprobado?vigencia=1&proyecto=1
---
- :x: GET /plan_trabajo_docente/preasignaciones/{vigencia}
- :white_check_mark: GET /preasignacion/?vigencia=1
---
- :x: GET /plan_trabajo_docente/preasignaciones_docente/{docente}/{vigencia}
- :white_check_mark: GET /preasignacion/docente?docente=1&vigencia=1

**Comment by NeFaWaltPint** [comment]
### Nota

Se ha generado commit directo a develop: https://github.com/udistrital/sga_plan_trabajo_docente_mid/commit/69501c8b1718210dec46e0d610ffa4d3778ca88b

**Comment by NeFaWaltPint** [comment]
### Estructura según lineamiento

```bash
├── conf
│   └── app.conf 
├── controllers 
│   ├── asignacion.go
│   ├── docente.go
│   ├── espacio_academico.go
│   ├── espacio_fisico.go
│   ├── plan.go             
│   ├── preasignacion.go 
│   └── reportes.go
├── docker-compose.yml  
├── Dockerfile     
├── entrypoint.sh               
├── LICENSE      
├── main.go
├── models               
│   ├── espacio_academico.go
│   ├── horario.go
│   ├── parametro.go        
│   ├── plan_trabajo_docente.go
│   └── tercero.go          
├── README.md                   
├── routers           
│   ├── commentsRouter_controllers.go
│   └── router.go    
├── services             
│   ├── asignacion.go                  
│   ├── docente.go                         
│   ├── espacio_academico.go
│   ├── espacio_fisico.go
│   ├── plan.go 
│   ├── preasignacion.go
│   └── reportes.go     
├── sonar-project.properties 
├── static
│   ├── img
│   └── templates
├── swagger
│   ├── swagger.json
│   └── swagger.yml
└── utils
    └── utils.go
```

### Manejo pánico
[defer en controlador](https://github.com/udistrital/sga_plan_trabajo_docente_mid/blob/develop/controllers/asignacion.go#L30) `defer errorhandler.HandlePanic(&c.Controller)`
[routing errors](https://github.com/udistrital/sga_plan_trabajo_docente_mid/blob/develop/routers/router.go#L14) `beego.ErrorController(&errorhandler.ErrorHandlerController{})`
